CREATE TABLE test_files
(
    name CHARACTER VARYING NOT NULL PRIMARY KEY,
    content CHARACTER VARYING NOT NULL,
    created_at CHARACTER VARYING NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at CHARACTER VARYING NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE compiled_tests
(
    name CHARACTER VARYING NOT NULL PRIMARY KEY,
    content CHARACTER VARYING NOT NULL,
    created_at CHARACTER VARYING NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at CHARACTER VARYING NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE test_runs
(
    id SERIAL NOT NULL PRIMARY KEY,
    name CHARACTER VARYING NOT NULL,
    compiled_code CHARACTER VARYING NOT NULL,
    duration BIGINT NOT NULL,
    passed BOOLEAN NOT NULL,
    ran_at CHARACTER VARYING NOT NULL DEFAULT CURRENT_TIMESTAMP,
);